import { Link } from 'wouter';
import {
  Aperture,
  ArrowLeft,
  CheckCircle2,
  CircleDot,
  Cpu,
  Gauge,
  GitBranch,
  Layers3,
  RadioTower,
  ShieldAlert,
  Waypoints,
} from 'lucide-react';

const architecture = [
  { label: 'Environment model', detail: 'Temperature, pressure, humidity, and vibration are sampled from the simulation service to form the operating envelope.', icon: Gauge },
  { label: 'Synthetic track model', detail: 'A generated target track supplies position, confidence, bearing, elevation, range, and error for demonstration only.', icon: Waypoints },
  { label: 'Predictive health', detail: 'Health projection translates simulated thermal and degradation signals into a readable risk horizon.', icon: ShieldAlert },
  { label: 'Adaptive control', detail: 'The control layer turns environmental state into a recommendation and simulated pan / tilt compensation.', icon: GitBranch },
];

const roadmap = [
  ['01', 'Interface contract', 'Freeze telemetry schemas and polling semantics before any device adapter work.'],
  ['02', 'Hardware adapter', 'Add an isolated integration boundary for approved sensor and camera feeds.'],
  ['03', 'Bench validation', 'Compare simulator output with instrumented bench conditions under controlled review.'],
  ['04', 'Governed deployment', 'Introduce permissions, audit records, and safety review before any field-facing capability.'],
];

function About() {
  return (
    <div className="min-h-[100dvh] bg-transparent text-slate-100">
      <header className="sticky top-0 z-40 border-b border-slate-800/90 bg-slate-950/90 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="/" data-testid="link-about-home" className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-md border border-teal-300/40 bg-teal-300/10 text-teal-300"><Aperture size={21} strokeWidth={1.5} /></div>
            <div><div className="text-sm font-extrabold tracking-[0.2em] text-slate-100">AERONEX <span className="text-teal-300">GP</span></div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-slate-500">System brief</div></div>
          </Link>
          <Link href="/" data-testid="link-return-dashboard" className="flex items-center gap-2 rounded border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-semibold text-slate-300 hover:border-teal-300/40 hover:text-teal-200"><ArrowLeft size={14} /> Return to console</Link>
        </div>
      </header>

      <main className="mx-auto max-w-[1180px] px-4 py-10 sm:px-6 sm:py-16 lg:px-8">
        <div className="mb-14 max-w-3xl animate-enter">
          <div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-teal-300"><CircleDot size={13} /> system information / 02</div>
          <h1 className="text-4xl font-extrabold tracking-tightest text-slate-50 sm:text-6xl">A calm surface for a complex sky.</h1>
          <p className="mt-6 max-w-2xl text-base leading-relaxed text-slate-400">AeroNex GP is a simulation-first high-altitude anti-drone operations console. It helps a technical operator see how environmental change would influence a modeled tracking system — without implying that a physical system is connected.</p>
        </div>

        <section className="mb-7 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
          <div className="rounded-lg border border-amber-300/25 bg-amber-300/5 p-6 sm:p-8">
            <div className="flex items-center gap-3 text-amber-200"><div className="flex h-9 w-9 items-center justify-center rounded border border-amber-300/30 bg-amber-300/10"><RadioTower size={17} /></div><span className="font-mono text-[10px] font-medium uppercase tracking-[0.16em]">non-negotiable boundary</span></div>
            <h2 className="mt-7 text-2xl font-bold text-amber-50">This console is a simulation.</h2>
            <p className="mt-3 text-sm leading-relaxed text-amber-100/65">No camera, sensor, actuator, aircraft, or physical countermeasure is connected. The target is synthetic. Telemetry is generated by a REST simulation loop for SIH presentation use. Control inputs only change the simulated state.</p>
            <div className="mt-7 grid gap-3 text-xs text-amber-100/70 sm:grid-cols-3"><div className="border-l border-amber-300/30 pl-3"><CheckCircle2 size={14} className="mb-2 text-amber-200" /><span>safe to explore</span></div><div className="border-l border-amber-300/30 pl-3"><CheckCircle2 size={14} className="mb-2 text-amber-200" /><span>no field telemetry</span></div><div className="border-l border-amber-300/30 pl-3"><CheckCircle2 size={14} className="mb-2 text-amber-200" /><span>no hardware control</span></div></div>
          </div>
          <div className="console-grid rounded-lg border border-slate-700/60 bg-slate-900/80 p-6 sm:p-8">
            <div className="font-mono text-[10px] uppercase tracking-[0.16em] text-slate-500">design intent</div>
            <blockquote className="mt-8 border-l-2 border-teal-300/50 pl-5 text-xl leading-relaxed text-slate-200">“Every signal is legible. Every state change has a consequence. Nothing is presented as more real than it is.”</blockquote>
            <div className="mt-8 flex items-center gap-3 border-t border-slate-800 pt-5 font-mono text-[10px] uppercase tracking-[0.13em] text-slate-600"><Cpu size={15} className="text-teal-300" /> operator-first / simulation-safe</div>
          </div>
        </section>

        <section className="mb-16 pt-8">
          <div className="mb-6 flex items-end justify-between gap-4"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-teal-300">01 / signal architecture</div><h2 className="mt-2 text-2xl font-bold text-slate-100">What the operator is reading</h2></div><div className="hidden font-mono text-[10px] uppercase tracking-[0.12em] text-slate-600 sm:block">rest polling / typed contracts</div></div>
          <div className="grid gap-px overflow-hidden rounded-lg border border-slate-800 bg-slate-800/80 md:grid-cols-2">{architecture.map(({ label, detail, icon: Icon }, index) => <div key={label} className="bg-slate-900/95 p-6" data-testid={`card-architecture-${index}`}><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded border border-teal-300/20 bg-teal-300/5 text-teal-300"><Icon size={15} /></div><h3 className="text-sm font-semibold text-slate-200">{label}</h3></div><p className="mt-4 max-w-sm text-xs leading-relaxed text-slate-500">{detail}</p></div>)}</div>
        </section>

        <section className="mb-16 grid gap-8 lg:grid-cols-[.8fr_1.2fr]">
          <div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-teal-300">02 / operating model</div><h2 className="mt-2 text-2xl font-bold text-slate-100">From atmosphere to response</h2><p className="mt-4 text-sm leading-relaxed text-slate-500">The dashboard keeps the cause-and-effect chain close: environment changes, tracking behavior moves, health projection responds, and adaptive control explains its recommendation.</p></div>
          <div className="relative space-y-3">{['Atmospheric reading', 'Tracking state', 'Health projection', 'Adaptive recommendation'].map((item, index) => <div key={item} className="flex items-center gap-4 rounded border border-slate-800 bg-slate-900/70 p-4"><span className="font-mono text-[10px] text-teal-300">0{index + 1}</span><span className="text-sm font-semibold text-slate-200">{item}</span><span className="ml-auto text-[10px] text-slate-600">{index === 0 ? 'input' : index === 3 ? 'operator cue' : 'derived signal'}</span></div>)}</div>
        </section>

        <section className="border-t border-slate-800 pt-10">
          <div className="mb-7"><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-teal-300">03 / future boundary</div><h2 className="mt-2 text-2xl font-bold text-slate-100">Hardware integration roadmap</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-500">The current build stops at the simulation boundary. Any future integration must remain isolated, observable, and reviewed before it can influence a real device.</p></div>
          <div className="grid gap-3 md:grid-cols-4">{roadmap.map(([number, title, detail]) => <div key={number} className="rounded-lg border border-slate-800 bg-slate-900/70 p-5"><div className="font-mono text-2xl text-slate-700">{number}</div><div className="mt-5 text-sm font-semibold text-slate-200">{title}</div><p className="mt-3 text-xs leading-relaxed text-slate-500">{detail}</p></div>)}</div>
        </section>

        <footer className="mt-16 flex flex-col justify-between gap-2 border-t border-slate-800/80 pt-4 font-mono text-[9px] uppercase tracking-[0.13em] text-slate-600 sm:flex-row"><span>AeroNex GP // system brief</span><span>simulation boundary active by design</span></footer>
      </main>
    </div>
  );
}

export default About;